### ISSUE TITLE
Please post some representative detection result images or videos and benchmark results

### ISSUE THREAD

**Issue by wwdok** [YonghaoHe/LFD-A-Light-and-Fast-Detector#10]
As the title said, thanks !

**Comment by YonghaoHe** [comment]
@wwdok  we have put some qualitative results at the end, please revisit [widerface readme](https://github.com/YonghaoHe/LFD-A-Light-and-Fast-Detector/tree/master/WIDERFACE_train) and [tt100k readme](https://github.com/YonghaoHe/LFD-A-Light-and-Fast-Detector/tree/master/WIDERFACE_train).

**Comment by jinfagang** [comment]
@YonghaoHe Image were 404

**Comment by YonghaoHe** [comment]
@jinfagang you may need proper proxy.
