### ISSUE TITLE
Errors when running prediect.py

### ISSUE THREAD

**Issue by on-your-way** [YonghaoHe/LFD-A-Light-and-Fast-Detector#13]
Win10-x64, Pycharm
Errors in line 455 of turbojpeg.py:

```
lib_path = os.path.join(os.path.dirname(__file__), 'libs')
libturtojpeg_path_list = [os.path.join(lib_path, file_name) for file_name in os.listdir(lib_path) if file_name.lower().startswith('libturbojpeg')]

# multiple paths may be got, choose the one with the longest chars
target_libturbojpeg_path = max(libturtojpeg_path_list)
turbojpeg = TurboJPEG(lib_path=target_libturbojpeg_path)

```
error message:
_

> target_libturbojpeg_path = max(libturtojpeg_path_list)
> ValueError: max() arg is an empty sequence

_
It seems like the lack of some files?

**Comment by on-your-way** [comment]
I overcame this problem by compiling the libjpeg-turbo project and using its turbojpeg.dll file temporarily.
And unfortunately, another error appears in line 4 of nms.py:

> from .libs import nms_ext
> ImportError: cannot import name 'nms_ext' from 'lfd.model.utils.libs'

It seems like missing nms_ext.py file?

**Comment by YonghaoHe** [comment]
@on-your-way you should compile first, please carefully read README.md

**Comment by on-your-way** [comment]
Thanks very much!
I solved it by your reminding.
