### ISSUE TITLE
测试精度问题

### ISSUE THREAD

**Issue by Watebear** [YonghaoHe/LFD-A-Light-and-Fast-Detector#14]
你好，我直接运行了 “WIDERFACE_LFD_XS.py“ 这个脚本，大约一天半的时间完成了1000个epoch的训练。
接下来运行 evaluation.py 脚本获取测试结果。

在使用 Retinaface.pytorch 中提供的 widerface_evaluate 文件夹下面的脚本进行测试，结果仅为：
Easy   Val AP: 0.5808434018537905
Medium Val AP: 0.6870650160504126
Hard   Val AP: 0.7353618031863371

这个测试结果与您公布的差距比较大。官方的 matlab 脚本我运行以后发现只绘制了3张图，图中也没有 LFD对应的曲线及数值上的指标。

 请问我该怎么做，希望得到您的帮助，非常感谢！

**Comment by Watebear** [comment]
> @Watebear 这里应该有问题，我建议使用matlab脚本运行，记得修改matlab里面的代码，主要是显示的legend，否则会覆盖。

我测了您的模型，发现数值也很低，都是0.6左右，matlab代码我研究下怎么改，如果方便的话，您是否能贴一下修改哪些地方；另外我对照公式看看那份测试脚本精度低的原因，因为之前用它测 retinaface，结果是正常的。谢谢您的回复。

**Comment by Watebear** [comment]
> @Watebear 这里应该有问题，我建议使用matlab脚本运行，记得修改matlab里面的代码，主要是显示的legend，否则会覆盖。
我用官方脚本测试了您的模型，easy 和 ，medium 都在 0.8 以上，但hard 只有 0.7x。 LFD项目中提供了多种 head，请问您测试中最好的模型，是哪种组合？ 通过netron可视化后，发现您公布的模型用的是最简单的设计。是否是网络结构的不同导致的测试结果的差异？

**Comment by YonghaoHe** [comment]
@Watebear 我建议可以用我预训练好的模型做一下测试，先确保测出来的结果是没问题的，然后再测你自己训出来的。
