### ISSUE TITLE
May you release a cpu-based inference version?

### ISSUE THREAD

**Issue by on-your-way** [YonghaoHe/LFD-A-Light-and-Fast-Detector#15]
As is known to all, it is better using CUDA for the training procedure. However, it is not practical for inference since many edge devices have not a GPU/CUDA hardway, such as my Surface.
In your README file, it is your wish that making LFD popular as YOLO series. So, I suggest that you release a cpu-based (even arm-based) inference version for edge devices, just like the [Libfacedetection](https://github.com/ShiqiYu/libfacedetection).

**Comment by YonghaoHe** [comment]
@on-your-way you mean Intel CPU?

**Comment by on-your-way** [comment]
> @on-your-way you mean Intel CPU?

yes

**Comment by jinfagang** [comment]
@on-your-way What do u suggest way to deploy CPU version? libtorch? tvm? openvino?

**Comment by YonghaoHe** [comment]
@on-your-way @jinfagang OPENVINO is the first choice for deployment on Intel CPU. You can implement yourself.

**Comment by jinfagang** [comment]
@YonghaoHe I am current trained some other dataset found that FP rate of LFD is a little high.

**Comment by on-your-way** [comment]
> @on-your-way @jinfagang OPENVINO is the first choice for deployment on Intel CPU. You can implement yourself.



> @on-your-way What do u suggest way to deploy CPU version? libtorch? tvm? openvino?

Thanks for suggesting. I am used to use the DNN module of OpenCV and have not tried others yet.

**Comment by on-your-way** [comment]
@YonghaoHe Thanks. I will try it.
