### ISSUE TITLE
Custom datset too many positives

### ISSUE THREAD

**Issue by jinfagang** [YonghaoHe/LFD-A-Light-and-Fast-Detector#16]
I tried train a single class dataset of hand:
 here is the result:

![image](https://user-images.githubusercontent.com/21303438/112435912-523d2000-8d80-11eb-9c87-da64fb56bc98.png)

It looks like a lot of false positives.....

**Comment by jinfagang** [comment]
am using class thresh to 0.5 already

**Comment by YonghaoHe** [comment]
@jinfagang  I think it is an easy task. Maybe something is not properly configured.

**Comment by jinfagang** [comment]
@YonghaoHe Where could be the reason? I have trained the model fully I think since the loss doesn't decreae anymore.

Also I have generated all negative images. And I have tried model such as YoloV5S, it performance normally at least doesn't have so many FPs.

**Comment by YonghaoHe** [comment]
@jinfagang you can show more details. I think there are something wrong .

**Comment by jinfagang** [comment]
@YonghaoHe I tried again and I found result should normal, but FP is inevatiable even I set thresh to 0.89

Seems a common problem in hand detection.

**Comment by YonghaoHe** [comment]
@jinfagang I still think that this task is not so difficult. If your dataset is publicly available, I can try it.

**Comment by jinfagang** [comment]
@YonghaoHe Yes. but it's in yolo format.

Here is the Baidu disk link of the dataset: https://pan.baidu.com/share/init?surl=H0YH8jMEXeIcubLEv0W_yw (c680)

**Comment by jinfagang** [comment]
@YonghaoHe  I have tried yolov5s which is much more stable than LFD performance. Both on recall and box regression accuracy

**Comment by YonghaoHe** [comment]
@jinfagang OK, I will try it .

**Comment by jinfagang** [comment]
@YonghaoHe Sure.
