### ISSUE TITLE
How to improve your hard set quality ?

### ISSUE THREAD

**Issue by docongminh** [YonghaoHe/LFD-A-Light-and-Fast-Detector#17]
You mentioned that LFFD v2 `greate improvement on Hard Set`. And i want know that:
- What is different between V2 and V1(tips, trick about training process, backbone, data,..) to get this quality ?
Thank you so much ! Nice research

**Comment by YonghaoHe** [comment]
@docongminh I list some key points that improve the performance:
1. wider range for the first head [4, 20] (vs [10, 20])
2. backbone with BN
3. focal loss + iou loss
4. head with GN and sharing heads
5. more reasonable region sampler

these are new things in LFD, and they may do big favors.

**Comment by docongminh** [comment]
@YonghaoHe  thank you !
In your paper, you mentioned that without BN makes latency lower than BN. So, In V2 you were trade-off between latency and accuracy ?

**Comment by YonghaoHe** [comment]
@docongminh at that time, BN is a indivisual op in TRT during inference. But now BN can be absorbed in Conv in TRT, which means no extra time added.

**Comment by docongminh** [comment]
@YonghaoHe  Many thanks, that's clealy

**Comment by docongminh** [comment]
So, anything change when use `ncnn optimizer` with V2 model ?

**Comment by YonghaoHe** [comment]
@docongminh someone has made it, check [issue](https://github.com/YonghaoHe/LFD-A-Light-and-Fast-Detector/issues/3)
