### ISSUE TITLE
[BUG] RandomBBoxCropRegionSampler can not handle image size smaller than 512

### ISSUE THREAD

**Issue by jinfagang** [YonghaoHe/LFD-A-Light-and-Fast-Detector#18]
```
/lfd/data_pipeline/sampler/region_sampler.py", line 300, in crop_from_image
    image[max(0, crop_y):min(im_h, crop_h + crop_y), max(0, crop_x):min(im_w, crop_w + crop_x)]
ValueError: could not broadcast input array from shape (0,400,3) into shape (191,400,3)


```

Default behavior seems using (crop_size, crop_size) as target size, if set crop_size to 512, it will got this error fianlly (here I set to 400).

Does this a bug?

**Comment by jinfagang** [comment]
```
crop_region = (crop_x, crop_y, self._crop_size, self._crop_size)
```
I think this is xywh, so the cropped can not be performed if input image is smaller than crop_size_

**Comment by jinfagang** [comment]
@YonghaoHe Please have look, the logic seems not properly.... pls have a inference on the code logic.

**Comment by YonghaoHe** [comment]
@jinfagang crop_size can be any number. So if you use the latest code?

**Comment by jinfagang** [comment]
@YonghaoHe I am not sure if you really notice the exceptions in your code. Let me explain:

Please look at L139 at regionsampler:

```
 crop_region = (crop_x, crop_y, self._crop_size, self._crop_size)

        new_bboxes = []
        new_labels = []
        for i, bbox in enumerate(scaled_bboxes):
            new_x = max(0, bbox[0] - crop_x)
            new_y = max(0, bbox[1] - crop_y)
            new_w = min(self._crop_size, bbox[0] + bbox[2] - crop_x) - new_x - 1
            new_h = min(self._crop_size, bbox[1] + bbox[3] - crop_y) - new_y - 1
            if new_w <= 1 or new_x >= self._crop_size or new_h <= 1 or new_y >= self._crop_size:
                continue
            new_bboxes.append([new_x, new_y, new_w, new_h])
            new_labels.append(labels[i])

        sample['image'] = crop_from_image(image, crop_region)
```

You mean crop size can be smaller than 512? then, inside `corp_from_image` function, your crop region will be:

```
xywh
wh will be crop_size, lets say 128 23
```

In function:

```

def crop_from_image(image, crop_region):
    """
    crop a region from the given image
    :param image:
    :param crop_region: x, y , w, h
    :return:
    """
    im_w = image.shape[1]
    im_h = image.shape[0]

    crop_x, crop_y, crop_w, crop_h = crop_region

    if image.ndim == 3:
        image_crop = numpy.zeros((crop_h, crop_w, 3), dtype=image.dtype)
    else:
        image_crop = numpy.zeros((crop_h, crop_w), dtype=image.dtype)

    image_crop[max(0, -crop_y):min(crop_h, im_h - crop_y), max(0, -crop_x):min(crop_w, im_w - crop_x)] = \
        image[max(0, crop_y):min(im_h, crop_h + crop_y), max(0, crop_x):min(im_w, crop_w + crop_x)]

    return image_crop
```

at this line:

```
image_crop[max(0, -crop_y):min(crop_h, im_h - crop_y), max(0, -crop_x):min(crop_w, im_w - crop_x)] = \
        image[max(0, crop_y):min(im_h, crop_h + crop_y), max(0, crop_x):min(im_w, crop_w + crop_x)]

```

I got this exception:

```
/lfd/data_pipeline/sampler/region_sampler.py", line 300, in crop_from_image
    image[max(0, crop_y):min(im_h, crop_h + crop_y), max(0, crop_x):min(im_w, crop_w + crop_x)]
ValueError: could not broadcast input array from shape (0,400,3) into shape (191,400,3)
```

Which means at a sitution, this value `max(0, crop_x):min(im_w, crop_w + crop_x)` become `0:0`.

Do u know why?  I indeed get this exception (not by loading train_negative_images, but by train on image smaller than 512, your regionsampler seems will sample with targetsize 512,

what will happen on these smaller images? And why I get the error? More importantly how to resolve it

**Comment by jinfagang** [comment]
I think I know where the issue is, and I believe most people train on custom dataset will have this issue.
I have made a patch perfected fix this rare cases in your code. Now every thing works fine.

The root reason got this is you didn't consider annotations maybe have xy and wh exceed the image. You can either constraint it in parser or constraint it in augmentation. (For future people might occured this)

@YonghaoHe

**Comment by YonghaoHe** [comment]
@jinfagang I will check it carefully very soon.

**Comment by YonghaoHe** [comment]
@jinfagang you are right. So calibration of annotation is supposed to be conducted in parsers. Parsers can be fully customized.

> I think I know where the issue is, and I believe most people train on custom dataset will have this issue.
> I have made a patch perfected fix this rare cases in your code. Now every thing works fine.
> 
> The root reason got this is you didn't consider annotations maybe have xy and wh exceed the image (this mostly happened when people using Yolo format as annotation, or doesn't clean annotation have negative values in it). Then you will hit this bug You can either constraint it in parser or constraint it in augmentation. (For future people might occured this)
> 
> @YonghaoHe

**Comment by RyanCV** [comment]
> Then you will hit this bug You can either constraint it in parser or constraint it in augmentation. (For future people might occured this)

Hi, I think the reason is the starting point (crop_x, crop_y) is outside of the original image, could you give more details on how to fix this bug? Thanks.  @YonghaoHe @jinfagang
