### ISSUE TITLE
是否能提供API文档？

### ISSUE THREAD

**Issue by ZhengHui-Z** [YonghaoHe/LFD-A-Light-and-Fast-Detector#26]
是否能提供接口调用的API文档

**Comment by YonghaoHe** [comment]
@ZhengHui-Z 您好，感谢关注。目前时间精力很有限，没有去做很规范完善的API文档。源代码尽可能做了注释，还有wiki也有大量参考，希望有帮助。

**Comment by ZhengHui-Z** [comment]
@YonghaoHe 谢谢您的回复，我将自行参考相关wiki和注释，辛苦了。
