### ISSUE TITLE
Error: onnx2tensorRT  in NVIDIA TX2

### ISSUE THREAD

**Issue by HT-Yuan** [YonghaoHe/LFD-A-Light-and-Fast-Detector#28]
Assertion failed: !isDynamic(tensor_ptr->getDimensions()) && "InstanceNormalization does not support dynamic inputs!".

do u have a solution ?

**Comment by YonghaoHe** [comment]
@HT-Yuan you can check the [readme](https://github.com/YonghaoHe/LFD-A-Light-and-Fast-Detector/blob/master/lfd/deployment/README.md) for more details.

**Comment by HT-Yuan** [comment]
> @HT-Yuan you can check the [readme](https://github.com/YonghaoHe/LFD-A-Light-and-Fast-Detector/blob/master/lfd/deployment/README.md) for more details.

ok,I found that this problem is caused by the difference of tensorRT version, thank you for your reply.

**Comment by Manideep08** [comment]
Did you find any solution for this?
I do use tx2 and tensorrt version is 7.1.3. 
Or any suggestion on deploying this in Jetson devices?

**Comment by HT-Yuan** [comment]
> Did you find any solution for this?
> I do use tx2 and tensorrt version is 7.1.3.
> Or any suggestion on deploying this in Jetson devices with jetpack 4.5 (tensorrt version is 7.1.x.x)?
> @YonghaoHe do you suggest any?

Hello,because of the TensorRT version, I did not run the code on TX2.(I tried to upgrade TensorRT to 7.2, but failed ) 。
In order to achieve fast face detection on TX2 , I used the Ultra face slim algorithm in my project
Link: https://github.com/Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB 
maybe  it can help you

**Comment by Manideep08** [comment]
Oh okay. My requirement is on a different use case and I have trained the model accordingly. Did you try deploying in onnx or any, which are supported in deepstream?

Then will have to figure a way for this!
