### ISSUE TITLE
OCR with LFD

### ISSUE THREAD

**Issue by RamatovInomjon** [YonghaoHe/LFD-A-Light-and-Fast-Detector#29]
Hi @YonghaoHe , thanks for your work!
I'm trying to train charachter detection model using LFD, I'm using traffic sign detector as an example. Which parameters and config do you suggest change to get better result?

**Comment by YonghaoHe** [comment]
@RamatovInomjon would you please share some examples with groundtruth ?

**Comment by RamatovInomjon** [comment]
![test2](https://user-images.githubusercontent.com/43458270/117173643-672cba80-ade6-11eb-9cea-ad21f4a13da0.jpg)
![test1](https://user-images.githubusercontent.com/43458270/117173649-685de780-ade6-11eb-988e-51f937f9de5c.jpg)
from my training set

**Comment by YonghaoHe** [comment]
@RamatovInomjon I see. You can try models for traffic sign without changes.

**Comment by RamatovInomjon** [comment]
what do you think? how to generate negative images for the dataset?
