### ISSUE TITLE
有移动端的性能测试吗？

### ISSUE THREAD

**Issue by zhongwenkun886** [YonghaoHe/LFD-A-Light-and-Fast-Detector#3]
如题

**Comment by zhongwenkun886** [comment]
赞一下大神。
例如用ncnn 或 MNN 或 TFlite 跑下普通高通芯片的安卓平台。

**Comment by ausk** [comment]
渣渣手机，麒麟960， ncnn

Size => FPS

size| 320|512
|:--:|:--:|:--:|
XS|8.5|3.5
S| 6 | 2.5
M| 3.5 | 1.5
L| 3 | 1.3

**Comment by scott-mao** [comment]
@ausk 请问你测试的速度在960上，是单核，还是多核速度
