### ISSUE TITLE
MSCOCO dataset is waiting for you.

### ISSUE THREAD

**Issue by ashuezy** [YonghaoHe/LFD-A-Light-and-Fast-Detector#4]
Can you put out a number among the best to know where you stand?

**Comment by Aktcob** [comment]
it's not enough without coco/voc, just face detection!

**Comment by YonghaoHe** [comment]
We are trying to apply LFD to COCO. A lot of things have be be tuned and it is time-consuming. But we make sure that results on COCO must be released in the future.

**Comment by jinfagang** [comment]
@YonghaoHe Is there any timeline on coco result? I am also curiosity about coco performance.

**Comment by dexception** [comment]
@YonghaoHe Can you share training steps? I would like to train your code on my 5 class dataset.

**Comment by YonghaoHe** [comment]
@jinfagang we are working on some other new ideas, and we  will conduct experiments on COCO, so I think performance on COCO will be released in 1-2 months.

**Comment by dexception** [comment]
@YonghaoHe That is a very time to wait. Can you share training steps for the time being?

**Comment by YonghaoHe** [comment]
@dexception training steps are described in README.md.

**Comment by dexception** [comment]
@YonghaoHe Let me train and get back to you. Thanks.
