### ISSUE TITLE
/lfd/lfd/data_pipeline/dataset/utils/turbojpeg.py", line 455, in <module>     target_libturbojpeg_path = max(libturtojpeg_path_list) ValueError: max() arg is an empty sequence

### ISSUE THREAD

**Issue by jinfagang** [YonghaoHe/LFD-A-Light-and-Fast-Detector#8]
/lfd/lfd/data_pipeline/dataset/utils/turbojpeg.py", line 455, in <module>
    target_libturbojpeg_path = max(libturtojpeg_path_list)
ValueError: max() arg is an empty sequence

**Comment by YonghaoHe** [comment]
@jinfagang I never encounter such error, more details ?

**Comment by jinfagang** [comment]
turns out manually copied turbojpeg.so to lfd solves
