### ISSUE TITLE
DataParallel

### ISSUE THREAD

**Issue by wobjtushisui** [YonghaoHe/LFD-A-Light-and-Fast-Detector#9]
DataParallel的GPU利用率比较低

**Comment by YonghaoHe** [comment]
@wobjtushisui 我在开发的时候注意到了这个问题。其实我发现，目前的服务器硬件条件已经非常好了，尤其是各种bus的带宽都已经非常高了，GPU与内存以及GPU之间的通信开销其实延时非常小，接近忽略不计。所以我在用DP的时候发现，速度一样可以跑到很快，至少在我训练用的机器上（RTX 2080TI x 4），四块卡的利用率都可以跑到90%以上。当然，我觉得DDP应该还会提升一点效率，但是碍于需要对架构里面的一些细节进行大量修改，所以当时先用上DP。不过后续，大版本更新的时候我会把DDP用上，同时再支持半精度训练。

**Comment by wobjtushisui** [comment]
没有用torch的接口，的确利用率可以

**Comment by YonghaoHe** [comment]
@wobjtushisui 是的，目前整个 data pipeline 都是不依赖任何框架的，它完全可以独立使用。
